language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphicsmagick
branches:
  only:
    - release
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: release
notifications:
  email:
    - secure: "VfFwbMK8q9nsnIyflszlgN0D7XEl/kAQLrhl8u2w296J12AKV/yGI7Tv1ejJ0B8DgeFeSRadETR6gQlC6RxHTS3Rg+80a08UAbUkynlzoKYIDl0LOBY5XADJZP04fHvpzoHmViolDKQWK1zHdhPe3GNRirNHd6vj+j8YOxq5sQm0YtNM44+Mi4ZRd3xNu5pOpLmCGaEcJIKT2axAf0Hs11dUEoAzBu522Etn6EhRWm4rPTm54+DEr9pdeiWUuYEQQ6Gy9vtsFhEtIVNu/KguEJODTuDzQxvz6VXhZ2yYZvBqRegZFJtzeCvoQXwz35JecfzH6gCvaxFQygqrKWAYdKS5I86VYW0dFDIcfKzm+yjN8NvNL9nhMq7kYf8egX8ZVlud5RXRqpxwQhkxLzadHfo1GnizuyhthEP632HtEz0P2p0hW5RRtwAzNYR1bwIisxJFCpBZnJgl7649D8msJKrKZUQ8S27M96aAkUzvWs89UjHtMN6yImgo3Mf/4DNIV9melfj3OAC3vDvCRCrKNYOaj6nQLoBHyCiDyUVmOK1gtzD0koQbZGBxSxh/L1H5K7gGaO3MqfURdJnkT3/L19p/gLFaY9e1l2DdGiXBAEBbtfnXvM/Xj5A19mgKJTHv6rUFgCzdsMY+uaNXmeq/GK9SUPdNkSb11oUhj6aIJ9k="
